width = input("Please enter the width of the room (in feet): ")
length = input("Please enter the lenth of the room (in feet): ")
fwidth = float(width)
flength = float(length)
print("The area of the room is", str(fwidth*flength), "square feet.")